# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages.defaults_pb2 as defaults_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  serialized_pb=_b('\n\ntest.proto\x1a\x0e\x64\x65\x66\x61ults.proto\"\xb2\x05\n\x04Test\x12\x13\n\x0b\x64oublenolen\x18\x01 \x02(\x01\x12\x17\n\ndoublelen2\x18\x02 \x02(\x01\x42\x03\xc8>\x02\x12\x12\n\nfloatnolen\x18\x03 \x02(\x02\x12\x16\n\tfloatlen2\x18\x04 \x02(\x02\x42\x03\xc8>\x02\x12\x12\n\nint32nolen\x18\x05 \x02(\x05\x12\x16\n\tint32len2\x18\x06 \x02(\x05\x42\x03\xc8>\x02\x12\x12\n\nint64nolen\x18\x07 \x02(\x03\x12\x16\n\tint64len2\x18\x08 \x02(\x03\x42\x03\xc8>\x02\x12\x13\n\x0buint32nolen\x18\t \x02(\r\x12\x17\n\nuint32len2\x18\n \x02(\rB\x03\xc8>\x02\x12\x13\n\x0buint64nolen\x18\x0b \x02(\x04\x12\x17\n\nuint64len2\x18\x0c \x02(\x04\x42\x03\xc8>\x02\x12\x13\n\x0bsint32nolen\x18\r \x02(\x11\x12\x17\n\nsint32len2\x18\x0e \x02(\x11\x42\x03\xc8>\x02\x12\x13\n\x0bsint64nolen\x18\x0f \x02(\x12\x12\x17\n\nsint64len2\x18\x10 \x02(\x12\x42\x03\xc8>\x02\x12\x14\n\x0c\x66ixed32nolen\x18\x11 \x02(\x07\x12\x18\n\x0b\x66ixed32len2\x18\x12 \x02(\x07\x42\x03\xc8>\x02\x12\x14\n\x0c\x66ixed64nolen\x18\x13 \x02(\x06\x12\x18\n\x0b\x66ixed64len2\x18\x14 \x02(\x06\x42\x03\xc8>\x02\x12\x15\n\rsfixed32nolen\x18\x15 \x02(\x0f\x12\x19\n\x0csfixed32len2\x18\x16 \x02(\x0f\x42\x03\xc8>\x02\x12\x15\n\rsfixed64nolen\x18\x17 \x02(\x10\x12\x19\n\x0csfixed64len2\x18\x18 \x02(\x10\x42\x03\xc8>\x02\x12\x11\n\tboolnolen\x18\x19 \x02(\x08\x12\x15\n\x08\x62oollen2\x18\x1a \x02(\x08\x42\x03\xc8>\x02\x12\x10\n\x08strnolen\x18\x1b \x02(\t\x12\x14\n\x07strlen2\x18\x1c \x02(\tB\x03\xc8>\x02\x12\x12\n\nbytesnolen\x18\x1d \x02(\x0c\x12\x16\n\tbyteslen2\x18\x1e \x02(\x0c\x42\x03\xc8>\x02')
  ,
  dependencies=[defaults_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doublenolen', full_name='Test.doublenolen', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doublelen2', full_name='Test.doublelen2', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='floatnolen', full_name='Test.floatnolen', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatlen2', full_name='Test.floatlen2', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='int32nolen', full_name='Test.int32nolen', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int32len2', full_name='Test.int32len2', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='int64nolen', full_name='Test.int64nolen', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int64len2', full_name='Test.int64len2', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='uint32nolen', full_name='Test.uint32nolen', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32len2', full_name='Test.uint32len2', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='uint64nolen', full_name='Test.uint64nolen', index=10,
      number=11, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint64len2', full_name='Test.uint64len2', index=11,
      number=12, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='sint32nolen', full_name='Test.sint32nolen', index=12,
      number=13, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sint32len2', full_name='Test.sint32len2', index=13,
      number=14, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='sint64nolen', full_name='Test.sint64nolen', index=14,
      number=15, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sint64len2', full_name='Test.sint64len2', index=15,
      number=16, type=18, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='fixed32nolen', full_name='Test.fixed32nolen', index=16,
      number=17, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixed32len2', full_name='Test.fixed32len2', index=17,
      number=18, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='fixed64nolen', full_name='Test.fixed64nolen', index=18,
      number=19, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixed64len2', full_name='Test.fixed64len2', index=19,
      number=20, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='sfixed32nolen', full_name='Test.sfixed32nolen', index=20,
      number=21, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sfixed32len2', full_name='Test.sfixed32len2', index=21,
      number=22, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='sfixed64nolen', full_name='Test.sfixed64nolen', index=22,
      number=23, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sfixed64len2', full_name='Test.sfixed64len2', index=23,
      number=24, type=16, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='boolnolen', full_name='Test.boolnolen', index=24,
      number=25, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boollen2', full_name='Test.boollen2', index=25,
      number=26, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='strnolen', full_name='Test.strnolen', index=26,
      number=27, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strlen2', full_name='Test.strlen2', index=27,
      number=28, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
    _descriptor.FieldDescriptor(
      name='bytesnolen', full_name='Test.bytesnolen', index=28,
      number=29, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='byteslen2', full_name='Test.byteslen2', index=29,
      number=30, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=721,
)

DESCRIPTOR.message_types_by_name['Test'] = _TEST

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  ))
_sym_db.RegisterMessage(Test)


_TEST.fields_by_name['doublelen2'].has_options = True
_TEST.fields_by_name['doublelen2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['floatlen2'].has_options = True
_TEST.fields_by_name['floatlen2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['int32len2'].has_options = True
_TEST.fields_by_name['int32len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['int64len2'].has_options = True
_TEST.fields_by_name['int64len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['uint32len2'].has_options = True
_TEST.fields_by_name['uint32len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['uint64len2'].has_options = True
_TEST.fields_by_name['uint64len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['sint32len2'].has_options = True
_TEST.fields_by_name['sint32len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['sint64len2'].has_options = True
_TEST.fields_by_name['sint64len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['fixed32len2'].has_options = True
_TEST.fields_by_name['fixed32len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['fixed64len2'].has_options = True
_TEST.fields_by_name['fixed64len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['sfixed32len2'].has_options = True
_TEST.fields_by_name['sfixed32len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['sfixed64len2'].has_options = True
_TEST.fields_by_name['sfixed64len2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['boollen2'].has_options = True
_TEST.fields_by_name['boollen2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['strlen2'].has_options = True
_TEST.fields_by_name['strlen2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
_TEST.fields_by_name['byteslen2'].has_options = True
_TEST.fields_by_name['byteslen2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\310>\002'))
# @@protoc_insertion_point(module_scope)
