# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: defaults.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='defaults.proto',
  package='',
  serialized_pb=_b('\n\x0e\x64\x65\x66\x61ults.proto\x1a google/protobuf/descriptor.proto:.\n\x06length\x12\x1d.google.protobuf.FieldOptions\x18\xe9\x07 \x01(\x05')
  ,
  dependencies=[google.protobuf.descriptor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


LENGTH_FIELD_NUMBER = 1001
length = _descriptor.FieldDescriptor(
  name='length', full_name='length', index=0,
  number=1001, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['length'] = length

google.protobuf.descriptor_pb2.FieldOptions.RegisterExtension(length)

# @@protoc_insertion_point(module_scope)
